### ISSUE TITLE
DBoW2 problems

### ISSUE THREAD

**Issue by hanghoo** [nicolov/simple_slam_loop_closure#1]
Hello,when I was compiling the package DBoW2, some errors come up:
lenovo@ubuntu:~/simple_slam_loop_closure/DBoW2/build$ make
Scanning dependencies of target DLib
[  6%] Creating directories for 'DLib'
[ 12%] Performing download step (git clone) for 'DLib'
Cloning into 'DLib'...
Note: checking out 'v1.1-nonfree'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 3a4a207... Merge pull request #6 from dorian3d/update/version
[ 18%] No patch step for 'DLib'
[ 25%] Performing update step for 'DLib'
[ 31%] Performing configure step for 'DLib'
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lenovo/simple_slam_loop_closure/DBoW2/build/dependencies/src/DLib-build
[ 37%] Performing build step for 'DLib'
Scanning dependencies of target DLib
[  3%] Building CXX object CMakeFiles/DLib.dir/src/DVision/BRIEF.cpp.o
In file included from /home/lenovo/simple_slam_loop_closure/DBoW2/build/dependencies/src/DLib/src/DVision/BRIEF.cpp:13:0:
/home/lenovo/simple_slam_loop_closure/DBoW2/build/dependencies/src/DLib/include/DVision/BRIEF.h:32:28: fatal error: opencv2/core.hpp: No such file or directory
 #include <opencv2/core.hpp>
                            ^
compilation terminated.
make[5]: *** [CMakeFiles/DLib.dir/src/DVision/BRIEF.cpp.o] Error 1
make[4]: *** [CMakeFiles/DLib.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [dependencies/src/DLib-stamp/DLib-build] Error 2
make[1]: *** [CMakeFiles/DLib.dir/all] Error 2
make: *** [all] Error 2

**Comment by nicolov** [comment]
What platform are you running on? I have only tested this on Ubuntu 16.04 w/ OpenCV3.

**Comment by hanghoo** [comment]
Ubuntu 14.04 + OpenCV2.4.8. In OpenCV3, there are many functions that I am not familiar with how to use them. But I will keep learning.

**Comment by zxw1992** [comment]
@Hoototo You have used wrong OpenCV version
