### ISSUE TITLE
no description about the vocabulary in readme file

### ISSUE THREAD

**Issue by mrgransky** [nicolov/simple_slam_loop_closure#11]
Is there any specific vocabulary from somewhere we should use to run this code?

I found  New College dataset (IJRR_2008_images), whereas vocabulary path is missing in the github description.

Cheers;
Farid

**Comment by nicolov** [comment]
You should be able to use the pre-trained vocabulary here: https://drive.google.com/file/d/0By6HmCDvB7WNbmJhZzhfVThNRDQ/view?usp=sharing

**Comment by mrgransky** [comment]
what is the file inside this folder needs to be addressed as the vocabulary?
Isn't it `resources/pose.txt`?

I am running the code like this:

`$ ./new_college /home/farid/WS_Farid/simple_slam_loop_closure/data/resources/ /home/farid/WS_Farid/simple_slam_loop_closure/data/newCollegeImg/`

because when I assign the folder (resources), I would get the following error:

```
OpenCV Error: Unknown error code -49 (Input file is empty) in cvOpenFileStorage, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/persistence.cpp, line 4484
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/persistence.cpp:4484: error: (-49) Input file is empty in function cvOpenFileStorage

Aborted (core dumped)
```

**Comment by nicolov** [comment]
Sorry for the delay. I've uploaded the images and vocabulary, and added instructions. I've also set up continuous integration with circleCI: you can have a look [here](
https://circleci.com/gh/nicolov/simple_slam_loop_closure) to see how to use the code.

**Comment by ihamieh** [comment]
i'm having the same error message and i'm not sure how to fix it! 

ThinkPad-T440s:~$ rosrun ORB_SLAM2 MonoAR Vocabulary/ORBvoc.txt /media/ish/New\ Volume/dataset/rgbd_dataset_freiburg1_rpy

ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular
OpenCV Error: Unknown error code -49 (Input file is empty) in cvOpenFileStorage, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/persistence.cpp, line 4484
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/persistence.cpp:4484: error: (-49) Input file is empty in function cvOpenFileStorage

Aborted (core dumped)
