### ISSUE TITLE
error about  frame_descriptor

### ISSUE THREAD

**Issue by zqnnn** [nicolov/simple_slam_loop_closure#13]
In file included from /home/zqn/loop_closure/simple_slam_loop_closure/src/new_college.cpp:11:0:
/home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:56:19: error: ‘Surf64Vocabulary’ was not declared in this scope
   std::unique_ptr<Surf64Vocabulary> vocab_;
                   ^
/home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:56:35: error: template argument 1 is invalid
   std::unique_ptr<Surf64Vocabulary> vocab_;
                                   ^
/home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:56:35: error: template argument 2 is invalid
/home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h: In constructor ‘slc::FrameDescriptor::FrameDescriptor(const string&)’:
/home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:17:12: error: request for member ‘reset’ in ‘((slc::FrameDescriptor*)this)->slc::FrameDescriptor::vocab_’, which is of non-class type ‘int’
     vocab_.reset(new Surf64Vocabulary(vocabulary_path));
            ^
/home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:17:22: error: expected type-specifier before ‘Surf64Vocabulary’
     vocab_.reset(new Surf64Vocabulary(vocabulary_path));
                      ^
/home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:18:53: error: base operand of ‘->’ is not a pointer
     std::cout << "Loaded vocabulary with " << vocab_->size() << " visual words.
                                                     ^
/home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h: In member function ‘void slc::FrameDescriptor::describe_frame(const cv::Mat&, DBoW2::BowVector&)’:
/home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:53:11: error: base operand of ‘->’ is not a pointer
     vocab_->transform(descriptors, bow_vec);
           ^
/home/zqn/loop_closure/simple_slam_loop_closure/src/new_college.cpp: In function ‘int main(int, char**)’:
/home/zqn/loop_closure/simple_slam_loop_closure/src/new_college.cpp:62:30: error: base operand of ‘->’ is not a pointer
       of << descriptor.vocab_->score(bow_vecs[i], bow_vecs[j]) << " ";
                              ^
CMakeFiles/new_college.dir/build.make:62: recipe for target 'CMakeFiles/new_college.dir/src/new_college.cpp.o' failed
make[2]: *** [CMakeFiles/new_college.dir/src/new_college.cpp.o] Error 1
CMakeFiles/Makefile2:164: recipe for target 'CMakeFiles/new_college.dir/all' failed
make[1]: *** [CMakeFiles/new_college.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nicolov** [comment]
Are you using the Docker setup?

**Comment by leyuan-sun** [comment]
The same problem 

> In file included from /home/zqn/loop_closure/simple_slam_loop_closure/src/new_college.cpp:11:0:
> /home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:56:19: error: ‘Surf64Vocabulary’ was not declared in this scope
> std::unique_ptr vocab_;
> ^
> /home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:56:35: error: template argument 1 is invalid
> std::unique_ptr vocab_;
> ^
> /home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:56:35: error: template argument 2 is invalid
> /home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h: In constructor ‘slc::FrameDescriptor::FrameDescriptor(const string&)’:
> /home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:17:12: error: request for member ‘reset’ in ‘((slc::FrameDescriptor*)this)->slc::FrameDescriptor::vocab_’, which is of non-class type ‘int’
> vocab_.reset(new Surf64Vocabulary(vocabulary_path));
> ^
> /home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:17:22: error: expected type-specifier before ‘Surf64Vocabulary’
> vocab_.reset(new Surf64Vocabulary(vocabulary_path));
> ^
> /home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:18:53: error: base operand of ‘->’ is not a pointer
> std::cout << "Loaded vocabulary with " << vocab_->size() << " visual words.
> ^
> /home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h: In member function ‘void slc::FrameDescriptor::describe_frame(const cv::Mat&, DBoW2::BowVector&)’:
> /home/zqn/loop_closure/simple_slam_loop_closure/src/frame_descriptor.h:53:11: error: base operand of ‘->’ is not a pointer
> vocab_->transform(descriptors, bow_vec);
> ^
> /home/zqn/loop_closure/simple_slam_loop_closure/src/new_college.cpp: In function ‘int main(int, char**)’:
> /home/zqn/loop_closure/simple_slam_loop_closure/src/new_college.cpp:62:30: error: base operand of ‘->’ is not a pointer
> of << descriptor.vocab_->score(bow_vecs[i], bow_vecs[j]) << " ";
> ^
> CMakeFiles/new_college.dir/build.make:62: recipe for target 'CMakeFiles/new_college.dir/src/new_college.cpp.o' failed
> make[2]: *** [CMakeFiles/new_college.dir/src/new_college.cpp.o] Error 1
> CMakeFiles/Makefile2:164: recipe for target 'CMakeFiles/new_college.dir/all' failed
> make[1]: *** [CMakeFiles/new_college.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

Do u solve the problem, I met the same error with u. Thanks ahead!

**Comment by leyuan-sun** [comment]
> Are you using the Docker setup?



> Are you using the Docker setup?

I found the reason of this error, could u plz upload the DBoW2 which you used, since right now the DBoW.h file does not support the Surf64
https://github.com/dorian3d/DBoW2/blob/3924753db6145f12618e7de09b7e6b258db93c6e/include/DBoW2/DBoW2.h#L61

**Comment by nicolov** [comment]
I just tried again with the Docker setup and everything's working fine. The CMakeLists pins a specific version of DBow2 from before Surf was removed.
