### ISSUE TITLE
Score always 1 so every entry in confusion matrix is 1. 

### ISSUE THREAD

**Issue by andrewpriddis** [nicolov/simple_slam_loop_closure#14]
I've run your example several times and the score always comes back as 1, so the confusion matrix is just a giant file full of 1's. When the image is generated it has no marks, every pixel is the same. Any ideas what is going wrong?

**Comment by nicolov** [comment]
I'm really sorry, I uploaded the wrong dictionary (BRIEF vs SURF). I've pushed a fix to master, you can see the confusion matrix generated in CircleCI: https://20-68512744-gh.circle-artifacts.com/0/root/project/out/confusion_matrix.png

**Comment by andrewpriddis** [comment]
Thanks!
