### ISSUE TITLE
creating bag of words file

### ISSUE THREAD

**Issue by MeghaMaheshwari** [nicolov/simple_slam_loop_closure#16]
I have a sequence of images with loop closure and I would like to create my own bag of words file. Could you tell me on how I can proceed to create my won bag of words file. Is it sufficient to feed my images to the dbW02 library and save the generated file to a text file? Do i need to do something more?

**Comment by nicolov** [comment]
I think so, but I've never tried, sorry.

**Comment by MeghaMaheshwari** [comment]
Are you using any custom available BoW than? From your code i felt like you are creating your own Bag of Words?

**Comment by nicolov** [comment]
Are you talking about making a new BoW *dictionary*, or just running on your own images?

**Comment by MeghaMaheshwari** [comment]
Yes talking about new Bow dictionary

**Comment by nicolov** [comment]
Sorry, I've never tried to create a new dictionary using that library.
