### ISSUE TITLE
About surf64_k10L6.voc.gz

### ISSUE THREAD

**Issue by Tacode** [nicolov/simple_slam_loop_closure#17]
Thanks for your work. This repos doesn't seem to have the code to generate surf64_k10L6.voc.gz, so I wander how  surf64_k10L6.voc.gz was generated.

**Comment by nicolov** [comment]
I got it from the library used for loop closure detection [here](https://github.com/dorian3d/DLoopDetector). I believe [this](https://github.com/dorian3d/DBoW2) has the code to train a new one, but it's just a vocabulary, so you should be able to keep using the default one unless your images look very different.
