### ISSUE TITLE
run "./build/new_college ./scripts/data/surf64_k10L6.voc.gz ./scripts/data  " 

### ISSUE THREAD

**Issue by zzl20** [nicolov/simple_slam_loop_closure#18]
Hi~, When I ran this command"./build/new_college ./scripts/data/surf64_k10L6.voc.gz ./scripts/data ", I encountered some errors：
Loading vocabulary from data/surf64_k10L6.voc.gz
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
Looking forward to your reply soon!

**Comment by nicolov** [comment]
Are you using the provided docker and sure you're not mistyping anything? That command is tested in CI so should be good.

**Comment by nicolov** [comment]
Please refer to the CircleCI scripts in case you run into any issue with the readme: https://github.com/nicolov/simple_slam_loop_closure/blob/master/.circleci/config.yml
